commit
Azure/communication-ui-library pull request #1186
Opened 2021-11-30 22:29 UTC by JamesBurnside

# What

# Why

# How Tested

# Process & policy checklist

- [ ] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

2021-11-30 22:41 UTC, mgamis-msft approved these changes

2021-12-01 01:21 UTC, alcail approved these changes

2021-12-01 18:24 UTC, prprabhu-ms requested changes
You sure?

2021-12-02 17:11 UTC, JamesBurnside commented
> You sure?

Lol I was walking someone through our CI, pull request, CD stuff in our repo and this was just a quick example, but I like this got two approvals! 😄

2021-12-02 17:11 UTC, closed without merging