Update calling dependency
Azure/communication-ui-library pull request #4055
Opened 2024-01-24 22:39 UTC by carocao-msft

# What
Update calling dependency

# Why

# How Tested

# Process & policy checklist

- [ ] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

2024-01-24 22:50 UTC, JamesBurnside requested changes
Make sure to update the common-versions.json file also

2024-01-25 21:41 UTC, dmceachernmsft approved these changes

2024-01-25 21:49 UTC, JamesBurnside approved these changes

2024-01-25 21:50 UTC, dmceachernmsft approved these changes

2024-01-25 21:54 UTC, edwardlee-msft approved these changes

2024-01-25 22:08 UTC, merged