Drop userID from isMutedChanged event
Azure/communication-ui-library pull request #413
Opened 2021-05-31 23:41 UTC by prprabhu-ms

# What

* Breaking change to CallAdapter API
* Drops the userId field from isMutedChanged event.

# Why

* Base Calling event doesn't include the user ID.
* The event *always* triggers for the local user (that's why base SDK doesn't include user ID).
* This was the *only place* where the user ID reported was the one stored in the stateful client context, the one provided by Contoso. In the case of CallComposite, this happens to be the same as the actual ACS ID because it's extracted from the token provided when creating the adapter. This is potentially very confusing because all other instances where a user ID is reported, the ID comes from the ACS services.
* Dropping this allows us to stop using the `getIdFromToken` hack and stop storing the user ID entirely in the adapter state (it's not needed anywhere else).

Profit!

# How Tested

`rush build`
`rush test`

# Process & policy checklist

- [x] I have updated the project documentation to reflect my changes if necessary.
- [x] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [x] This change causes current functionality to break.

2021-05-31 23:43 UTC, JamesBurnside approved these changes

2021-05-31 23:46 UTC, PorterNan requested changes
There are 2 places triggers this event, one for local user one for remote user, please also check ParticipantSubcriber.ts to and check the one for remote user

UserID is necessary, because it is the one to distinguish different users including local and remote one

2021-06-01 00:04 UTC, prprabhu-ms commented
> There are 2 places triggers this event, one for local user one for remote user, please also check ParticipantSubcriber.ts to and check the one for remote user
> 
> UserID is necessary, because it is the one to distinguish different users including local and remote one

I had seen ParticipantSubscriber but missed that it was trigger the same event.
The string named event `emit()` calls means that IDEs can't easily help find all the places an event is triggered :( Nor does CI catch the problem in this PR. :'(

My original complaint still stands though. For all the remote participants, the user ID is the one reported from ACS backend. Only when it's the local user, the ID is the one we extracted (and saved in adapter context) from the token. This is confusing / not robust.

Do we really want to treat the two cases: local user was (un)muted and remote user was (un)muted in the same way like this?

* I think we should treat local user specially. Contoso likely wants to have very different response to when the local user is muted vs remote is muted.
* `isLocalScreenSharingActiveChanged` is only emitted for local user (and does not include userId). It would be consistent to similarly have `isLocalMutedChanged` and `isMutedChanged` (naming discussion below).


We're quite inconsistent in what events refer to local vs. remote vs. both users.

Currently:

* Only applies to local: `isLocalScreenSharingActiveChanged`
* Only applies to remote: `isSpeakingChanged`, `displayNameChanged`.
* Applies to both local and remote: `isMutedChanged`.
* Special case: `videoStreamsUpdated` applies only to remote, but there seems to be no way for Contoso to subscribe to this event.

I think we should keep local vs remote events separate:

* Only applies to local: `isLocalScreenSharingActiveChanged`, `isLocalMutedChanged`.
* Only applies to remote: `isRemoteSpeakingChanged`, `remoteDisplayNameChanged`, `isRemoteMutedChanged`, `remoteVideoStreamsUpdated` (also plumb this one through so Contoso can subscribe to it).

Would like to get some agreement on this before landing any API breaking changes.

@DominikMe @PorterNan

2021-06-01 19:11 UTC, prprabhu-ms commented
Moved discussion to team thread.

Will create new PR for a broader API change.

2021-06-01 19:11 UTC, closed without merging