[Calling][Bug]Remove pptlive
Azure/communication-ui-library pull request #4365
Opened 2024-03-28 22:48 UTC by ShaunaSong

# What

# Why

# How Tested

# Process & policy checklist

- [ ] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

2024-03-28 22:49 UTC, Leah-Xia-Microsoft approved these changes

2024-03-28 22:54 UTC, Leah-Xia-Microsoft requested changes
Seems like we need to run rush build to update the API view as well

2024-03-28 22:55 UTC, dmceachernmsft reviewed
please update the API files as well otherwise this will still show PPTLive in the published files 
![image](https://github.com/Azure/communication-ui-library/assets/94866715/bb5a72dd-d34a-4777-9b5e-40f6367f654d)

2024-04-01 16:09 UTC, JamesBurnside commented on packages/communication-react/review/beta/communication-react.api.md
> +    onReactionClick(reaction: Reaction_2): Promise<void>;
There's changes here that look unexpected

2024-04-01 16:11 UTC, alkwa-msft approved these changes

2024-04-01 16:11 UTC, JamesBurnside approved these changes

2024-04-01 16:13 UTC, merged