Fix adapter function always needs a bind
Azure/communication-ui-library pull request #552
Opened 2021-07-08 09:17 UTC by PorterNan

Update adapter to arrow function
Remove CallAdapter from public api

# What

# Why

# How Tested

# Process & policy checklist

- [ ] I have updated the project documentation to reflect my changes if necessary.
- [ ] I have read the [CONTRIBUTING](https://github.com/Azure/communication-ui-library/blob/main/CONTRIBUTING.md) documentation.

**Is this a breaking change?**

- [ ] This change causes current functionality to break.

2021-07-08 15:51 UTC, alkwa-msft commented
Can we link the bug/issue that this change is related to in order to build some context?

2021-07-08 15:55 UTC, JamesBurnside commented on packages/communication-react/review/communication-react.api.md
> -export class AzureCommunicationCallAdapter implements CallAdapter {
unintentionally removed?

2021-07-08 15:56 UTC, JamesBurnside commented on packages/communication-react/review/communication-react.api.md
> -export class AzureCommunicationCallAdapter implements CallAdapter {
nice!

2021-07-08 15:57 UTC, JamesBurnside approved these changes

2021-07-08 16:20 UTC, prprabhu-ms requested changes
I don't think we should do this.

See https://github.com/Azure/communication-ui-library/pull/449#discussion_r652949367

Arrow functions create a new function object per instance of the class and are an anti-pattern.
Is it surprising to users that they need to bind methods to the object if they're using them as callback. That is standard JavaScript behavior, right?

2021-07-09 16:55 UTC, anjulgarg approved these changes

2021-07-14 20:48 UTC, alcail approved these changes

2021-07-19 19:53 UTC, alkwa-msft commented
@PorterNan  can we close this since we did the binding as part of prathmesh's change?

2021-07-22 17:38 UTC, PorterNan commented
Will open another one to remove some apis from our public api files

2021-07-22 17:38 UTC, closed without merging